[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/addresses/*"
  to = "/.netlify/functions/api/addresses/:splat"
  status = 200

